version: "3.4"
services:
  jaeger:
   container_name: "jaeger-container"
   ports:
     - 4317:4317   #grpc
     - 4318:4318   #http
     - 16686:16686 #UI
  identitydb:
    container_name: identitydb_container
    restart: always
    ports:
     - 1433:1433
    volumes:
     - identitydb_volume:/var/opt/mssql
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=Password12*
  graphdb:
    container_name: graphdb_container
    restart: always
    ports:
     - 1444:1433
    volumes:
     - identitydb_volume:/var/opt/mssql
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=Password12*
  rabbitmq: 
    container_name: rabbitmq_container
    restart: always
    ports:
      -5672:5672
      -15672:15672
  elasticsearch:
   container_name: elasticsearch_container
   ports:
    - 9200:9200
   environment:
    - xpack.security.enabled=false
    - "discovery.type=single-node"
    - ELASTIC_USERNAME=elastic
    - ELASTIC_PASSWORD=DkIedPPSCb
   volumes:
    - elastic_db:/usr/share/elasticsearch/data
  kibana:
   ports:
    - 5601:5601
   environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
   depends_on:
    - elasticsearch
  kibana:
   ports:
    - 5601:5601
   environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
   depends_on:
    - elasticsearch