version: "3.4"
services:
  elasticsearch:
   container_name: "elasticsearch_container"
   expose:
    - 9200
   environment:
    - xpack.security.enabled=false
    - "discovery.type=single-node"
    - ELASTIC_USERNAME=elastic
    - ELASTIC_PASSWORD=DkIedPPSCb
   networks:
    - es-net
   ports:
    - 9200:9200
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
  kibana:
   container_name: "kibana_container"
   environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
   expose:
    - 5601
   networks:
    - es-net
   depends_on:
    - elasticsearch
   ports:
    - 5601:5601
   volumes:
    - kibana-data:/usr/share/kibana/data
  jaeger:
   container_name: "jaeger-container"
   ports:
    - 4317:4317   #grpc
    - 4318:4318   #http
    - 16686:16686 #U
  rabbitmq:
   container_name: "rabbitmq_container"
   ports:
    - 5672:5672 
    - 15672:15672 
  identitydb:
    container_name: "identitydb_container"
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - identitydb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password12*
  graphdb:
    container_name: "graphdb_container"
    restart: always
    ports:
      - "1444:1433"
    volumes:
      - graphdb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password12*